### ISSUE TITLE
Can't e-mail invoices (dokku install)

### ISSUE THREAD

**Issue by adev73** [siwapp/siwapp-ror#312]
After I finally managed to install siwapp on Dokku (thanks @dnwilson!), I now find it refuses to send e-mails.

I've configured all the required fields, including hostname, and all I get is the error:

> 501 Syntax: HELO hostname

I can telnet to the SMTP server & manually enter the HELO command, so I don't think the problem is with my mail server.

Is there any way I can turn on extra logging to try to determine what's happening, and why my e-mails won't send? I'm not skilled with Ruby on Rails, or Heroku, or Herokuish/Dokku.

**Comment by adev73** [comment]
> I've configured all the required fields, including hostname

I meant including _domain_, of course

**Comment by dnwilson** [comment]
@adev73 did you get this sorted already?

**Comment by adev73** [comment]
Hi @dnwilson,

No - I gave up and went back to the old version of Siwapp - and managed to get that one sending emails instead.

I’m no longer using the Rubynon Rails version, as I’m just not comfortable with the environment; even if the app looks so much better.

Cheers,
Ade.

**Comment by sonic182** [comment]
> After I finally managed to install siwapp on Dokku (thanks @dnwilson!), I now find it refuses to send e-mails.
> 
> I've configured all the required fields, including hostname, and all I get is the error:
> 
> > 501 Syntax: HELO hostname
> 
> I can telnet to the SMTP server & manually enter the HELO command, so I don't think the problem is with my mail server.
> 
> Is there any way I can turn on extra logging to try to determine what's happening, and why my e-mails won't send? I'm not skilled with Ruby on Rails, or Heroku, or Herokuish/Dokku.

Actually your problem was being inside a docker container, and having the postfix or similar outside docker

For that case you could used mailchimp or similar to make the app connect to an external SMPT server
